### ISSUE TITLE
`isNew` property is always true

### ISSUE THREAD

**Issue by omanizer** [alonronin/mockingoose#13]
First off, thanks for writing this fantastic library.  It makes mocking much easier.

I've noticed that model.isNew always returns true.  Most of the time when running a find query I would expect this to not be the case.

Would this be worth implementing?  Would it make sense to be default unless an override is specified?

Such as:
```
mockingoose.MyModel.toReturn(sequence, 'findOne', {isNew: true})
```

**Comment by alonronin** [comment]
Hi,

Thank you very much for using it, it sure made my life easier 😄 

IMO the `isNew` property is not relevant in mocking and i'm creating a mongoose Document from the mock data, so the `isNew` is always true.

If you really need that, submit a PR, I would be happy to review it.
