### ISSUE TITLE
[Question]: How do you test instance methods

### ISSUE THREAD

**Issue by mikeyGlitz** [alonronin/mockingoose#16]
I have a schema for users:

```js
const userShcema = new Schema({
  name: {
    first: String,
   last: String,
  },
  password: { type: String, required: true },
  email: { type: String, required: true },
};
```
This schema has a method `comparePasswords` which compares a password against a bcrypt hash.
```js
userSchema.methods.comparePasswords =  function comparePasswords(candidatePassword){
...
}
```

How do I test code which depends on the instance method?
How would I stub out this instance method to return an expected value?
Would that look like?
```js
mockingoose.User.toReturn({ email, password, comparePasswords: () => true }, 'findOne');
```

**Comment by alonronin** [comment]
your instance functions would work as expected. just assert the returned data or error if you have one.
