### ISSUE TITLE
Mock doesn't seem to be working on code that uses models

### ISSUE THREAD

**Issue by mikeyGlitz** [alonronin/mockingoose#17]
I have 3 files: my test file, my model, and a wrapper which uses the model to create entries in the database. I've structured the code in a way that the test calls functions from the wrapper code which uses the model directly. When I investigated why my tests were failing, I noticed it was because I was missing fields that should have been returned with my mocks. What I was getting back from the model mock was simply what I had put into the save call.

_User.js_
```js
import mongoose, { Schema } from 'mongoose';
const { Types } = Schema;

const userSchema = new Schema({
  name: {
     first: String,
     last: String,
  },
  email: { type: String, required: true },
  password: {type: String, required: true }
};

export default mongoose.model('User', userSchema);
```

_Handler.js_
```js
...
export const loginUser = (req, resp ) => User.findOne({ email: req.body.email })
.then( result => {
  if (!result) return resp.sendStatus(404);
  return resp.status(200).json(result.getView());
})
.catch( err => resp.sendStatus(500));
```

_Handler.test.js_
```js
describe('#loginUser', () => {
  beforeEach(() => mockingoose.resetAll());
  it('Logs in a valid user'), (done) => {
    const user = casual.user;   // Use pre-defined casual generator to generate user with random data
    mockingoose.User.toReturn({ ...user, createdAt: Date.now() }, 'findOne' });

   const req = { body: { user } };
   const resp = { sendStatus: jest.fn(), status: jest.fn() };

    loginUser(req, resp)
      .then(() => {
        expect(status.mock.calls[0][0]).toEqual(200);  // Fails. Result from DB mock is null instead of user
  });
});
```

Instead of getting a return value from the database, I get a null value. My mock for status is an exception because status arg0 is not defined. Doing a `console.log` on sendStatus, I can see that my 404 is being sent back from my handler mock.

**Comment by alonronin** [comment]
see #18
