### ISSUE TITLE
Having problems with errors not being thrown

### ISSUE THREAD

**Issue by mikeyGlitz** [alonronin/mockingoose#18]
I have 3 files: my test file, my model, and a wrapper which uses the model to create entries in the database. I've structured the code in a way that the test calls functions from the wrapper code which uses the model directly. I have code which uses validation and want to test if the handler works correctly when validation fails. Instead of an error like I'm expecting, test is passing. Upon investigating, I noticed that mockingoose is simply giving me back what I put into the handler call instead of throwing the error like I told it to.

_User.js_
```js
import mongoose, { Schema } from 'mongoose';
const { Types } = Schema;

const userSchema = new Schema({
  name: {
     first: String,
     last: String,
  },
  email: { type: String, required: true },
  password: {type: String, required: true }
};

export default mongoose.model('User', userSchema);
```

_Handler.js_
```js
...
export const createUser= (req, resp ) => User.create({ email: req.body.user})
.then( result => {
  if (!result) return resp.sendStatus(404);
  return resp.status(200).json(result.getView());
})
.catch( err => {
  if (err.code === 11000) return resp.sendStatus(401);
  return resp.sendStatus(500);
});
```

_Handler.test.js_
```js
describe('#createUser', () => {
  beforeEach(() => mockingoose.resetAll());
  it('Rejects registration from a user that already exists'), (done) => {
    const user = casual.user;   // Use pre-defined casual generator to generate user with random data

    // Error class for validation failure
    class DuplicateRecordError extends Error {
      constructor(...params) {
        super(...params);
        this.code = 11000;
      }
    }

    mockingoose.User.toReturn(new DuplicateRecordError(), 'save' });

   const req = { body: { user } };
   const resp = { sendStatus: jest.fn(), status: jest.fn() };

    loginUser(req, resp)
      .then(() => {
        expect(sendStatus.mock.calls[0][0]).toEqual(401);  // Fails. Throws exception. calls[0][0] not defined.
  });
});
```

Instead of getting a 401 from my response mock, I receive a 200 from `resp.status`. Putting a `console.log` into my handler code, I can see that whenever I'm running my tests the database call to `.create` is returning an object instead of throwing an error. The object that I get back from mockingoose is simply the object which I passed into my handler instead of the error.

**Comment by alonronin** [comment]
did you try with `new Error()` to see what you get?

is seems you got more under the hood happening there. i'd appreciate a working example so I can try it also.

**Comment by mikeyGlitz** [comment]
I created a test project with the code which was causing problems.
https://github.com/mikeyGlitz/user-account-service

**Comment by alonronin** [comment]
v2.6.0 fixes this issue, please upgrade.

**Comment by mikeyGlitz** [comment]
Confirmed: new version fixed the problem.
