### ISSUE TITLE
Support for Mongoose 5.x

### ISSUE THREAD

**Issue by b1f6c1c4** [alonronin/mockingoose#19]
Since `mongoose^4.13.9` is in `peerDependencies` AND `dependencies`, when I run `yarn`, `mongoose^5.0.1` will be installed at `node_modules/mongoose` while `mongoose^4.13.9` will be install at `node_modules/mockingoose/node_modules/mongoose`.
Then `mockingoose` mocks the wrong `mongoose`, and everything messed up.

My suggestion is to remove `mongoose^4.13.9` from `dependencies` and change `mongoose^4.13.9` to `mongoose^4.13.9 || ^5.0.1`.

**Comment by b1f6c1c4** [comment]
[https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md) may be helpful.

**Comment by alonronin** [comment]
this is in the roadmap.

**Comment by alonronin** [comment]
will happen on the next major version, stay tuned.
