### ISSUE TITLE
support for aggregate

### ISSUE THREAD

**Issue by igrek2000** [alonronin/mockingoose#22]
it would be nice to have a mock for aggregate or some workaround

**Comment by igrek2000** [comment]
Using as workaround: 
`            const fn = function exec() {
                return [{_id: '1', numberOfManagers: 2, numberOfContributors: 3 }];
            }
            MyModel.aggregate = jest.fn(() => { return { exec: fn }});`

**Comment by alonronin** [comment]
I would appreciate a PR
