### ISSUE TITLE
access to jest.fn()'s [enhancement]

### ISSUE THREAD

**Issue by kevinfez** [alonronin/mockingoose#25]
It would be nice if the mocked jest.fn()'s were easily available so that toHaveBeenCalledWith() can used.

For example, when testing a getXXX function, I don't really need to test that the value I just mocked is being returned as much as I need to make sure that the findOne function was actually called on the model with the proper parameters. 

In a couple contrived jest tests, I'd see this working as such:
```
it('should call findOne with the _id', async () => {
  await getMyDocument('some_id');
  expect(mockingoose.MyDocument.findOne).toHaveBeenCalledWith({_id: 'some_id'});
});

it('should call findOne with the _id and isActive flag', async () => {
  await getMyDocument('some_id?isActive=true');
  expect(mockingoose.MyDocument.findOne).toHaveBeenCalledWith({_id: 'some_id', isActive: true});
});
```

**Comment by alonronin** [comment]
Actually you have it directly on mongoose instance. Currently all operation on `Query` are `jest.fn` and the `exec` also. I need also to make the `save` a `jest.fn` (I don't know why I didn't 😄).

Thanks to your Issue I've added a TODO to the README.

**Comment by kevinfez** [comment]
ah I see; I guess in case other people find their way here, this seems to be a valid way of doing it:
```
expect(MyDocument.Query.prototype.findOne).toHaveBeenCalledWith({ _id: 'some_id' }, undefined);
```
fyi, if you forget the second parameter then you'll get a blank failure message, pays to remember that while the second parameter to ```findOne``` is optional, jest's ```expect``` doesn't care and expects you to declare that it will be ```undefined```.

But the real gotcha in this is that the ```jest.fn``` never clears, so you must change your ```beforeEach``` to be as such:
```
beforeEach(() => {
  mockingoose.resetAll();
  MyDocument.Query.prototype.findOne.mockClear();
});
```
Otherwise one test's calls will carry over into another test's expectation and you will get false-positives.

**Comment by alonronin** [comment]
@kevinfez btw, mongoose always runs the `exec` method so you can check it in your assertion.

Also you can use `jest.clearAllMocks()` in the beforeEach function.

**Comment by kevinfez** [comment]
@alonronin oh cool, ```jest.clearAllMocks()``` definitely will help reduce mistakes.

I checked ```MyDocument.Query.prototype.exec.mock.calls``` and all I get is ```[ [] ]```.
So that's useful for ```expect(MyDocument.Query.prototype.exec).toHaveBeenCalled();``` but unless I'm doing something wrong I don't think it'll allow me to check the query being executed
