### ISSUE TITLE
How to access save document params?

### ISSUE THREAD

**Issue by pradel** [alonronin/mockingoose#27]
Hey, first of thanks for this library, it is really helpful!

I wanted to know if there is a way to access the params passed down to a new document.
For example:
```javascript
// This is the function I want to test
const newUser = new UserModel({
  ...data
});
await newUser.save();

// This is my test
mockingoose.User.toReturn({}, 'save');

callMyFunction()

// here I would like to make an assert about the params
expect(mockingoose.User.save).toHaveBeenCalledWith(...);
```

**Comment by alonronin** [comment]
yes, all the prototypes on the Model are mocked:
https://github.com/alonronin/mockingoose/issues/25

**Comment by pradel** [comment]
Thanks for the quick response, I saw that but the problem is the save method is attached to a new object so how can I test the constructor params?

**Comment by pradel** [comment]
@alonronin can we reopen the issue since it is not resolved?

**Comment by kschiffer** [comment]
I would also really like this functionality.
Also, thanks for making this great library!
