### ISSUE TITLE
Update not changing the object

### ISSUE THREAD

**Issue by bytefluxio** [alonronin/mockingoose#30]
I have a question regarding the readme.
There you stated that it is intended, that update does not change anything.

> .update({ name: 'changed' }) // this won't really change anything

But shouldn't that actually change the name to changed? How else can we accurately test what the code is doing?

I might be missing something here :(

**Comment by alonronin** [comment]
no, it's a mock, no db is involved you are the who decide what is coming back from the mock using:

```js
mockingoose.Model.toReturn({ name: 'changed' }, 'update')
```

**Comment by lonix1** [comment]
I was also confused until I found this post. Maybe we should think of another example... :)

Thanks for mockingoose BTW, it's awesome!

**Comment by farajist** [comment]
Doesn't `.update({ name: 'changed' })` require the document to update as the second parameter ? My test couldn't pass without it !
