### ISSUE TITLE
TypeError: mongoose.model is not a function

### ISSUE THREAD

**Issue by artjomzab** [alonronin/mockingoose#34]
```
"@types/mongoose": "^5.0.15",
"mongoose": "^5.1.3",
"mockingoose": "^2.10.1"
```
category.schema.ts:

```ts
import { Schema } from 'mongoose';

export const CategorySchema = new Schema({
  name: String,
  description: String,
}, { timestamps: true });
```

In the test:

```ts
let categoryModel: Model<Category> = mongoose.model('Category', CategorySchema);
mockingoose.Category
      .toReturn([mockCategory], 'find');
```

When I run the test I get 

`TypeError: mongoose.model is not a function`

Any ideas why I get the error?

**Comment by alonronin** [comment]
Try without destructuring Schema:

```js
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
```

**Comment by artjomzab** [comment]
@alonronin thanks for the hint, however it makes no difference, still get the error. I think it is related to the mongoose version. For mongoose v4 it used to work.

**Comment by alonronin** [comment]
@artjomzab can you clone this repo and run:
```bash
npm i && npm i mongoose && npm t
```
are the tests passes at your end?

**Comment by artjomzab** [comment]
@alonronin sorry took me a while 😄 https://github.com/artjomzab/mockingoose-test just pull the repo and run `npm test`. The test is located here: https://github.com/artjomzab/mockingoose-test/tree/master/src/modules/cookie/repository
