### ISSUE TITLE
How do you use distinct?

### ISSUE THREAD

**Issue by wootwoot1234** [alonronin/mockingoose#39]
I tried this but I get an error

        mockingoose.Account.toReturn(
            ["593cebebebe11c1b06efff0372","593cebebebe11c1b06efff0373"],
            "distinct"
        );

Error: 

    ObjectParameterError: Parameter "obj" to Document() must be an object, got 593cebebebe11c1b06efff0372

So then I try passing it an array of document objects but it just returns the documents.  How di I get it to return just an array or strings?

Here's the code inside the function I'm testing:

            const accountIDs = await Account.find({
                userID: "test",
                lastLoginAttemptSuccessful: true
            }).distinct("_id");

**Comment by alonronin** [comment]
I personally don't think you should care about that, you should plan you mock in advance to return desired output.

Mocks should be dumb.
