### ISSUE TITLE
Suggestion: Expose mocked jest function

### ISSUE THREAD

**Issue by davidnghk01** [alonronin/mockingoose#47]
Case:
I want to known what parameter passed to mongoose function (E.X. find, countDocuments...etc.)

Example code: 
query.js
```js
// Let use User Model in __tests__/User.js
import user from "User"
export queryUserByName = (name) => user.find({
   name
})
```

My Test
```
import mockingoose from "mockingoose"
import {queryUserByName} from "./query"
import User from "./User"

test("Test find user by name", async () => {
  mockingoose.User.toReturn([{name: "David", email: "david.ng.dev@gmail.com"}], "find")
  const result = queryUserByName("David")
  const callParams = User.Query.prototype["find"].mock.calls[1][0]
  expect(callParams).toEqual({name: David})
})
```

Although this work but this one is undocumented way.

May be direct expose jest fn or add it to README.md ?

**Comment by alonronin** [comment]
@davidnghk01 I'd appreciate a PR 👍

**Comment by stieg** [comment]
Sounds like a good idea in principle.  Wonder what it would take to insert jest mock functions as a sort of interceptor between the various operations.  @alonronin have you played with this at all?  Know the feasibility of this or have any pointers about on this?

**Comment by stieg** [comment]
I would like this as well as it would really help with tests.  Should be doable with the use of [mockClear](https://jestjs.io/docs/en/mock-function-api.html#mockfnmockclear) and some additions to the already existing code.  Let's see where this rabbit goes

**Comment by stieg** [comment]
So... interesting issue comes from this.  Because mockingoose overwrites the Query operation prototype function sthe same jest mock function exists for _every_ Query operation across every model.  What this effectively means is that if I expose access to this, it will work for testing one model at a time.  But if you use more than one at a time there is a potential for conflict.  I guess the question here is whether it would be accepted to implement this simpler version first or would you reject that patch @alonronin in favor of a more complex one where every Query op on every Model gets its own mock.  LMK

**Comment by stieg** [comment]
Hey @alonronin I have posted https://github.com/alonronin/mockingoose/pull/49.  Have  a look when you have time. Cheers.

**Comment by andreialecu** [comment]
Found myself looking for this as well. Wouldn't a simpler and more powerful implementation simply allow passing a function instead of an object?

So OPs test more or less becomes:

```javascript
test("Test find user by name", async () => {
  let callParams;
  const mockReturn = (params) => {
    callParams = params;
    return [{name: "David", email: "david.ng.dev@gmail.com"}];
  });
  mockingoose.User.toReturn(mockReturn, "find")
  const result = queryUserByName("David")
  expect(callParams).toEqual({name: David})
})
```

I think this would be a much simpler change to implement than #49.

**Comment by andreialecu** [comment]
Opened #50.

**Comment by stieg** [comment]
@andreialecu If I have read and understood the code correctly you are effectively implementing a poor man's mock function with the following code:
```js
  let callParams;
  const mockReturn = (params) => {
    callParams = params;
    return [{name: "David", email: "david.ng.dev@gmail.com"}];
  };
```
Unfortunately your code is restricted in its current form relative to full mock functions.  What happens if two calls to `queryUserByName` happen?  In the code you gave above the `callParams` value would only contain the parameters of the second call and the values of the first call would be lost.  Jest Mock Functions already handle this by persisting all calls so it's better to use that then re-invent the wheel no?

I'm not sure that #50 solves this issue as a result, but it does add an extra bit of functionality that may be useful.

**Comment by andreialecu** [comment]
The approach is much more powerful because you can inspect the full mongoose Query object.

You can still pass in a custom `jest.fn().mockImplementation(() => someResult)` which you can then inspect via jest in any way you want.

**Comment by andreialecu** [comment]
The approach in PR #50 allows things like this:

```typescript
    it('should only query for non-hidden clubs', async () => {
      mockingoose.Club.toReturn((query: Query<Club>) => {
        expect(query.getQuery()).toHaveProperty('hidden', { $ne: true });
        return [];
      }, 'find');
      const clubs = await clubsService.getAllClubsPublic(''); // the implementation for this must ensure { hidden: { $ne: true } } is in the query
      expect(clubs).toBeDefined();
    });
```

**Comment by stieg** [comment]
I'm not saying that #50 isn't useful.  It most certainly is useful given the examples you have provided and should be considered for inclusion.  I am only saying that it does not resolve _this_ issue completely.  Put differently, your solution is not a feature complete replacement of a mock functions, hence why I believe it is not a full solution to this issue.

**Comment by andreialecu** [comment]
To reiterate. You're free to use any mocking framework you want with #50 and pass in your mocked function with much more control than any other approach:

https://jestjs.io/docs/en/mock-functions

```
const myMock = jest.fn();

myMock
  .mockReturnValueOnce([{name: "David", email: "david.ng.dev@gmail.com"}])
  .mockReturnValue([{name: "John", email: "john@gmail.com"}]);

mockingoose.User.toReturn(myMock, 'find');
const result1 = queryUserByName("David");
const result2 = queryUserByName("John")

inspect myMock.mock.<anything> here
```

**Comment by andreialecu** [comment]
One thing to keep in mind is that the approach in top level post is wrong in a way, which #50 addresses correctly.

You can have a query like:
`queryUserByName = (name) => user.find().where('name').equals(name);`

In this case the mocked `find()` call will not have the right parameters of the query, so the OP's code to check for them via mocks won't work. The conditions will be undefined, as the `find` mock is called at the wrong time.

The PR considers this scenario and properly exposes the `Query` object directly, which will be populated properly at the point that the query is (mockingly) sent to mongo.

**Comment by stieg** [comment]
Very valid point here @andreialecu.

**Comment by alonronin** [comment]
You raised some great points, maybe we can make mockingoose even simpler, inferring the OP from from the query itself.

Also currently mockgoose is focusing on jest, but I thought about making it agnostic.

I would like to hear your thoughts on a roadmap for version 3, also if any of you would like to join as a an official contributor, I will be glad.

**Comment by alonronin** [comment]
well, I liked @andreialecu angle on this, and I've decided to merge it for the next version.

@stieg thanx a log for opening our minds and @andreialecu thanx for your effort guys.

We should think on make it even simpler in next major version (infer query op, passing model to mockingoose directly etc.)
