### ISSUE TITLE
Access update and options when using findOneAndUpdate

### ISSUE THREAD

**Issue by eitanfar** [alonronin/mockingoose#52]
Hi, thanks for a great package, it's very helpful !

I'm trying to write a test for a service using the `getByIdAndUpdate`method (which uses the `getOneAndUpdate` method), and I need to check the update object and that the options are configured in a specific way.
The problem is that I can't seem to find a reference for either. Using `query.getQuery()` I get only the `_id` field and neither the options and update.
I've also thought it might be somewhere on the query object itself, seeing that it has options and update fields, but they were not what I send in the call.
Is there some way to receive those as well ?

Thanks in advance, 
Eitan

**Comment by alonronin** [comment]
you should supply the mock to return, mockingoose does nothing but mocking mongoose.

checkout: https://github.com/alonronin/mockingoose/blob/master/___tests___/index.test.ts#L238

**Comment by alonronin** [comment]
duplicate #30

**Comment by eitanfar** [comment]
I understand that currently this is not supported, but I'm asking to add this to the existing implementation. 
After all, when you mock the function you have all the info available: `(criteria, doc, options, callback)`. What I need (as well as in #30) are the `doc` and `update`.
A change to the `ReturnFunction` type would allow us to receive that needed information, something like:

```
type ReturnFunction = (
  param: mongoose.Query<any> | mongoose.Aggregate<any>, update: any, options: any
) => {};
```

Without this information, it's impossible to check that the service is updating the data correctly, which is the whole point of testing it.

**Comment by gornostal** [comment]
> you should supply the mock to return, mockingoose does nothing but mocking mongoose.

@alonronin 
I don't see how that answers the author's question.
I also can't find a method that would return me an update data:

```
      mockingoose(Cargo).toReturn(query => {
        expect(query.getQuery()).toEqual({ cargoId: CARGO_ID })  // <-- this passes
        expect(query.getUpdate()).toEqual({ newDoc }) // <-- this fails, because getUpdate() returns undefined
        return mockCargoDocument
      }, 'findOneAndUpdate')

      await Cargo.findOneAndUpdate({cargoId: CARGO_ID}, { newDoc })
```

**Comment by broldansaztrek** [comment]
I'm also having the same problem. on my _ReturnFunction_, I want to access what's being set on my _findOneAndUpdate_ but _query.getUpdate()_ returns an _undefined_ value.

**Comment by maqduni** [comment]
@eitanfar I see you closed the issue. Is it because you haven't gotten this answered or because you found a solution? I'm also looking for a way to test the update object that's being passed to the Mongo client.

**Comment by maqduni** [comment]
@alonronin I see you closed the issue, but I still can't find a way to test the update object. I have this statement and would like to test whether the correct update object is being passed to `findOneAndUpdate`:
```javascript
const $set = {};
$set[`address`] = `some address`;
const property = await this.PropertyModel.findOneAndUpdate({ _id: propertyId }, { $set }, { new: true });
```

I need to test the address value that's being passed in `$set`. How can I do it?

**Comment by alonronin** [comment]
check out https://github.com/alonronin/mockingoose/issues/25

**Comment by maqduni** [comment]
Sounds good, I used `const findOneAndUpdateSpy = jest.spyOn(PropertyModel, 'findOneAndUpdate');`
