### ISSUE TITLE
is filtering on toReturn possible?

### ISSUE THREAD

**Issue by jole78** [alonronin/mockingoose#53]
I know I'm probably trying to do something that this library isn't supposed to be solving but I thought I'd ask anyway, so here goes.

I have a mongoose model called Profile. A profile can have users. The problem is that some of these users should be filtered out in some circumstances so on the Profile model I have a method called getUsers which does some "magic" for finding the users.

So I wanna test this getUsers method and have setup some tests for it which looks something like this:

```javascript
      mockingoose("User").toReturn([user1, user2], "find");
      const result = await profile.getUsers();
      expect(result).toHaveLength(1);
```

so the gist here is that getUsers in this case should only return user1.

Profile.getUsers looks something like this:

`return this.model("User").where("userId", { $in: ids });`

The issue then. Well mokingoose always returns the 2 users I told it to...
The code "works" outside of the tests so the problem lies that I'm unable to test the actual getUsers function properly.

And as I said...this probably isn't supported right??

Anyway thanks for a great library, it otherwise solves a bunch of really complicated setup, so kudos!

**Comment by andreialecu** [comment]
Take a look at: https://github.com/alonronin/mockingoose/blob/master/README.md#mockingoosemodeltoreturnfn-operation--find

You should be able to inspect the query and return only what you need for specific queries.

**Comment by jole78** [comment]
Yes that's kind of my approach right now. It feels a little bit like I know too much of the internals of the method I'm testing though. If I basically tell the implementation of getUsers what to return. I don't know...it doesn't feel right basically.
But maybe in this case I probably need something that actually touches the real api/db but in memory. I know there's another mocking Lin fir mongoose that takes that approach but it requires a little bit more to work.
