### ISSUE TITLE
mockingoose breaks when `jest.resetAllMocks()` is called in between tests

### ISSUE THREAD

**Issue by calumpeak** [alonronin/mockingoose#57]
This is a pretty common pattern to have in a jest setup file or in an `afterEach` block to call `jest.resetAllMocks` to ensure that there is no leaking/shared values between test runs. 

As mockingoose sets up most of it's mocks in the global scope at import time instead of invocation time, anyone using `jest.resetAllMocks` will have their tests timeout. I believe this is also the issue with #36 .

I noticed in mockingoose's own tests it's only relying on `jest.clearAllMocks` instead of reset.

I'm happy to raise a PR to fix this issue if necessary.

**Comment by alonronin** [comment]
good catch. PR would be awesome!

**Comment by calumpeak** [comment]
@alonronin I'll see what I can do 👍

**Comment by luizzappa** [comment]
It seems to me that this bug is still happening
