### ISSUE TITLE
Problem with invoking `this.model('ModelName')` inside model hook.

### ISSUE THREAD

**Issue by SergeyPoluektov** [alonronin/mockingoose#58]
It's impossible to use `this.model('ModelName')` in a model hooks [Model.prototype.model()](https://mongoosejs.com/docs/api/model.html#model_Model-model).

For instance:
```
const schema = new mongoose.Schema({ name: String });
schema.pre('save', function(next) {
  this.model('ModelName'); // throw an error TypeError: this.model is not a function
});
```

I guess it's related to this code on line 267, where an object is assigned to the `model` property.
https://github.com/alonronin/mockingoose/blob/cc160bcd8ec0a787988c24cf5c159c53b8060574/src/index.ts#L256-L269

Is it possible to use other property name to store `{ modelName }` object, e.g. `__model`?

**Comment by alonronin** [comment]
you are correct `this.model` is not a function.

if you can provide a PR for this, it would be great!
