### ISSUE TITLE
Support Node 4.x

### ISSUE THREAD

**Issue by BenjaminPrice** [alonronin/mockingoose#6]
Please add support for node 4.x.

This package is exactly what I need but we have yet to upgrade from node 4.x as it's still not fully out of LTS - and still in maintenance.

From what I can see in the code, it would involve moving away from ES6 proxies and using object.observe instead.

**Comment by alonronin** [comment]
first of all, thanx for your interest in this project, this is indeed something i was also missing when wanted to test my mongoose code.

you can easily use it with node 4 with babel. there is a babel plugin for using Proxies now:
https://www.npmjs.com/package/babel-plugin-proxy

you should transpile it thru babel and that's it 😄 

I won't move away from es201x Proxy as I think it's great addition to the language.
