### ISSUE TITLE
For Model.create() -> .lean() is not a function

### ISSUE THREAD

**Issue by davidmeirlevy** [alonronin/mockingoose#63]
Consider this code:
`Article.create(data).lean()`

The test suggests a result:
model.toReturn(resolvedTestObj, 'save');

**Expected result**: Test should pass.

**Received result**: `TypeError: Article.create(...).lean is not a function`

**Comment by alonronin** [comment]
There is no `lean` method on `Model.create` return result. It already returns lean data in mongoose.

It is not a mockingoose issue. 

BTW, mockingoose mocks all methods automatically view the `Query` object of mongoose, even on `Model` methods.
