### ISSUE TITLE
Migrate To Official Mongoose Types

### ISSUE THREAD

**Issue by LuisOsta** [alonronin/mockingoose#68]
Due to the breaking change in the new types of Mongoose: https://github.com/Automattic/mongoose/issues/9606.
I'm not able to use this library with the new version of mongoose.

These are the errors I'm getting

```
node_modules/mockingoose/lib/index.d.ts:4:39 - error TS2314: Generic type 'Query<ResultType, DocType>' requires 2 type argument(s).

4 declare type ReturnFunction = (param: mongoose.Query<any> | mongoose.Aggregate<any>) => {};
                                        ~~~~~~~~~~~~~~~~~~~

node_modules/mockingoose/lib/index.d.ts:43:43 - error TS2314: Generic type 'Model<T>' requires 1 type argument(s).

43 declare const mockModel: (model: string | mongoose.Model<any, {}>) => Mock;
                                             ~~~~~~~~~~~~~~~~~~~~~~~
```

Would it be possible to migrate over to the new types?

**Comment by LuisOsta** [comment]
So I tried making a quick PR to do the upgrade but I think there was a big change in the way they are handling queries and documents. So it won't be a a trivial upgrade

**Comment by alonronin** [comment]
thanx, i'll try to check it out.

**Comment by alonronin** [comment]
I removed TypeScript completely from this lib and now everything works perfectly and supports latest mongoose version.
