### ISSUE TITLE
empty response

### ISSUE THREAD

**Issue by noamokman** [alonronin/mockingoose#7]
Hey,
Can we add an option for an empty response?
mockingoose.User.toReturn(null, 'findOne');

```js
User.findOne() // resolves as an object with id
```
Because of the ` new Model(mock);` [here](https://github.com/alonronin/mockingoose/blob/master/src/index.js#L27)

Let me know what you think,
Thanks!

**Comment by alonronin** [comment]
What is the motivation? if you have data, then it will most likely comeback as a Mongoose Model.

**Comment by noamokman** [comment]
I want to test an empty response from the find() query.
If no documents were found.
