### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by feRpicoral** [alonronin/mockingoose#70]
Giving that mockingoose is not using typescript since e48c08be98d827cdbb86086c12890ace110fab8e, it would be nice to have a `d.ts` file as it used to have to offer a better user experience.

**Comment by alonronin** [comment]
yep, i'm planning to do it. i'd appreciate a PR on it 😄

**Comment by feRpicoral** [comment]
If I have some time left I will have a look at it and see what I can do!

**Comment by tjarbo** [comment]
+1

**Comment by danieloprado** [comment]
Pull Request: #81
