### ISSUE TITLE
mockingoose(User).toReturn(new Error('My Error'), 'create'); doesnt throw error

### ISSUE THREAD

**Issue by OrrLumigo** [alonronin/mockingoose#74]
mockingoose(model).toReturn(new Error('My Error'), 'save');

return model.create({ name: 'name', email: 'name@email.com' }).catch(err => {
  expect(err.message).toBe('My Error');
});

this doesn't throw an exception

**Comment by alonronin** [comment]
please supply some a test repo with replication of this case.

**Comment by santgr11** [comment]
I'm having this issue, adding an error to save doesn't work, but using it in a findOne does

using something like the error is not thrown

```
mockingoose(Project).toReturn(new Error('test error'), 'save');

try {
      const result = await Project.create({});
      console.log('error not thrown');
    } catch (err) {
      console.log('error thrown', err);
    }
```
