### ISSUE TITLE
Getting MongooseError: Operation `todos.insertOne()` buffering timed out after 10000ms error message

### ISSUE THREAD

**Issue by technowar** [alonronin/mockingoose#77]
This is the test,
```
describe("POST /todos", () => {
  describe("Todos", () => {
    test("return created todo", async () => {
      const _data = {
        _id,
        created,
        status: "pending",
        subtasks: [],
        title: "Todo X"
      };

      Mockingoose(Todo).toReturn(_data, "save");

      const body = { title: "Todo X" };
      const data = await Todo.create(body);

      expect(data).toMatchObject(_data);
    }, 15000);
  });
});
```

The code I am trying to test,
```
const data = await Todo.create({
  title: req.body.title
});
```

**Comment by Parnswir** [comment]
I am getting the same error after upgrading to `mongoose@^6.0.0`. On 5.x your test should work.

**Comment by Parnswir** [comment]
Another workaround I just discovered is manually mocking `create`, assuming you use jest:

```js
jest.spyOn(Todo, "create").mockImplementationOnce(async () => _data);
```

**Comment by OliverFischer** [comment]
Hi all, 

starting from 6.x the authors of mongoose decided to shadow the original `save` function with 
`Model.prototype.$save = Model.prototype.save;`, so that mocking `save` does not work anymore. 
Modifying the index.js code to include `$save` for the ops enumeration
```
const ops = ['find', 'findOne', 'count', 'countDocuments', 'estimatedDocumentCount', 'distinct', 'findOneAndUpdate', 'findOneAndDelete', 'findOneAndRemove', 'findOneAndReplace', 'remove', 'update', 'updateOne', 'updateMany', 'deleteOne', 'deleteMany', 'save', 'aggregate', '$save'];
```
 and extending
```
if (!mock && op === 'save') {
      mock = this;
    }

    if (!mock && op === '$save') {
      mock = this;
    }
 // or ;-) at least a little bit better
if (!mock && op === op.includes('save')) {
      mock = this;
    } 
    
```
let all tests passes with 5.x and 6.x. May be @Parnswir you may change the code to make it work with both versions. Sadly I am stuck to mocha and sinon and searched for a way to depict the functionality of this great project to our needs/libs. 

Greetings

Olli

**Comment by danieloprado** [comment]
I've just made a PR #83 with @OliverFischer changes.

**Comment by OliverFischer** [comment]
> I've just made a PR #83 with @OliverFischer changes.

Hi @danieloprado : One thing I missed in my description was the adjustment of the `index.test.js `file. When working with mongoose 6, 
- should create returns mock
- should return error
needs to be adjusted too and become:
```
mockingoose(User).toReturn({ _id: '507f191e810c19729de860ea' }, '$save');
mockingoose(User).toReturn(error, '$save');
```
Sorry for that. By the way, imho backward compatibility is lost by simple replacement. May be a simple arrow fn or something like this (if the authors from mongoose decide to shadow more functions by prepending a $ :-) ) 
```
const opWrap = op => parseInt(mongoose.version[0]) >= 6 ? `$${op}` : op
```

**Comment by lbruno69** [comment]
Any updates?
