### ISSUE TITLE
Pre, Post hooks

### ISSUE THREAD

**Issue by datajohnny** [alonronin/mockingoose#8]
Hi, do you have any information about how to implement the pre and post functionality on models?

**Comment by alonronin** [comment]
can you attach an example project?

**Comment by datajohnny** [comment]
@alonronin  https://gist.github.com/datajohnny/20d30be5bffbc2b5f3feb03342106814

**Comment by alonronin** [comment]
We need to run Hooks manually at the mock.

This are supported Hooks:
http://mongoosejs.com/docs/middleware.html

Hooks mechanism is build using Kareem:
https://github.com/vkarpov15/kareem

Need to dig a bit more.

**Comment by omanizer** [comment]
FWIW, pre/post hooks seem to be working for me on mockingoose@2.10.1 and mongoose@4.13.9.  They only stopped working for me after I upgraded to mongoose@5.

**Comment by alonronin** [comment]
see https://github.com/alonronin/mockingoose/releases/tag/v2.12.0
