### ISSUE TITLE
Query.prototype.orFail() not supported?

### ISSUE THREAD

**Issue by fmigowski** [alonronin/mockingoose#80]
# Problem description
I'm trying to cover a scenario when `findOne` should fail and trigger `orFail`.
It works fine when I mock the result (when it finds by the property I'm passing). But it throws an exception when I try to simulate the `orFail` case.

* Reference: [Mongoose docs: orFail](https://mongoosejs.com/docs/api.html#query_Query-orFail)

# Failing Scenario
> Given mongoose adapter
> When fine one findOneById (adapter's method name)
> And the document does not exist in the database
> Then it should throw an error

Below you can see two scenarios, the first one it's when it finds the id and succeeds and the second it's when it doesn't find and it should throw an error.

## Test Code
```js
import { Model, model } from 'mongoose';
import * as mockingoose from 'mockingoose';

describe('Given mongoose adapter', () => {
  let mySomethingModel;
  let mongooseMySomethingAdapter;

  beforeEach(() => {
    myModel = model<MySomethingDocument>(MySomethingDocument.name, MySomethingSchema);
    mongooseMySomethingAdapter = new MongooseMySomethingAdapter(myModel);
  });

  describe('when find one by id', () => {
    describe('and the document exists in the database', () => {
      it('then it should return my something', async () => {
        const mySomething = {
          id: 'fa965c2c-d697-4736-b42b-1f703f65d18d'
        };

        mockingoose.MySomethingDocument.toReturn(mySomething, 'findOne');

        // THIS WORKS FINE!
        expect(
          await mongooseMySomethingAdapter.findOneById(
            'fa965c2c-d697-4736-b42b-1f703f65d18d'
          )
        ).toEqual(mySomething);
      });
    });

    describe('and the document does not exist in the database', () => {
      const id = 'fa965c2c-d697-4736-b42b-1f703f65d18d';
      it('then it should throw an error', async () => {
        mockingoose.MySomethingDocument.toReturn(null, 'findOne');

        // THIS DOESN'T WORK!
        await mongooseMySomethingAdapter.findOneById(id).catch((err) => {
          expect(err).toEqual(
            new DocumentNotFoundException(MySomethingDocument.name, id)
          );
        });
      });
    });
  });
});

 ```

## MongooseMySomethingAdapter
```js
export class MongooseMySomethingAdapter {
  constructor(mySomethingModel: Model<MySomethingDocument>) {}

  async findOneById(id: string): Promise<MySomething> {
    const result = await this.mySomethingModel
      .findOne({ id })
      .orFail(() => new DocumentNotFoundException(MySomethingDocument.name, id))
      .exec();
    return await this.mySomethingMapper.fromDocument(result);
  }
}
```

So when I try to set the `finOne` to return `null` or `undefined`, i.e. `mockingoose.MySomethingDocument.toReturn(null, 'findOne');`, it doesn't throw my custom exception and continues to the `mySomethinMapper.fromDocument`.

If I then mock to throw an error in `findOne`, i.e.`mockingoose.MySomethingDocument.toReturn(new Error('My error'), 'findOne');`, it throws this error (`Error('My error')`) but it doesn't throw my custom exception inside the `orFail` block.

So the question is, am I missing something? Or it doesn't support `orFail` yet?

**Comment by alonronin** [comment]
See if you can add support for it, would be much appriciated.
