### ISSUE TITLE
 TypeError: (0 , mockingoose_1.default) is not a function

### ISSUE THREAD

**Issue by lazizcodes** [alonronin/mockingoose#85]
In my TS project I am using mockingoose@2.15.2 as follows:
```ts
import MyModel from '../models/MyModel';
import mockingoose from 'mockingoose';

mockingoose(MyModel).toReturn(null, 'findOne');
```
I cannot understand why `mockingoose(MyModel)` throws `TypeError: (0 , mockingoose_1.default) is not a function` error.
Looks like this is a bug, or am I missing something?

**Comment by Rchitects** [comment]
> You have to import like this for version >= v2.14.0:
> 
> ```js
> import * as mockingoose from 'mockingoose'
> ```

This doesnt work for me. Im using 
`const mockingoose = require("mockingoose");`
To make it Work but with that i loose the types...

**Comment by moritz157** [comment]
I have tried out adding `"esModuleInterop": true` (mentioned [on StackOverflow](https://stackoverflow.com/questions/61524130/typescript-babel-import-causing-1-default-is-not-a-function)) but it doesn't work either. Losing types by using `require("...")` is not really an option in my opinion.

**Comment by Parnswir** [comment]
It seems that with v2.16.0 this issue is relevant again. Consider the following sample:

```ts
import * as mockingoose from 'mockingoose';
mockingoose(MyModel).toReturn([], 'find');
```
results in `Type 'typeof import("[...]/node_modules/mockingoose/types")' has no call signatures.` thrown by the TS compiler.

On the other hand, this:
```ts
import mockingoose from 'mockingoose';
mockingoose(MyModel).toReturn([], 'find');
```
will lead to `TypeError: (0 , mockingoose_1.default) is not a function` at runtime, even though the `types.d.ts` file introduced in 2.16.0 suggests it should work.

**Comment by GP-marco** [comment]
*bump* 
any news on this?
This is still blocking us from updating to the newest version

**Comment by lemonshumhk01** [comment]
problem still exists. Is this repo still under maintenance ?

**Comment by timondavis** [comment]
Still seems to be an issue.  any news?
