### ISSUE TITLE
Return different results for the same model

### ISSUE THREAD

**Issue by joh-klein** [alonronin/mockingoose#87]
I know, this might be a long shot, but maybe it is possible.

Right now, I am doing this:

```js
import { mocked } from 'ts-jest/utils';
import { Model } from '../models/model';

jest.mock('../models/model');

const mockedModel = mocked(Model, true);

mockedModel.aggregate.mockResolvedValueOnce(['data]).mockResolvedValueOnce(['other data]);
```

The idea is to have to different results for the same model since I have two different aggregations that can't be merged together.

Is/Would/Could this be possible with mockingoose?

**Comment by yurtaev** [comment]
You can use a function as a parameter like this:

```js
mockingoose(Model).toReturn((query) => {
  if (cond === 1) return 1
  if (cond === 2) return 2
  ...
})
```
